name: Editorconfig Linter Check

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Linter Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: dotnet format (apply fixes)
      run: dotnet format --verbosity diagnostic V8ed/V8ed.csproj

    - name: Commit dotnet format Fixes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Apply dotnet format fixes" || true
        git push origin HEAD:${{ github.head_ref }}

    - name: dotnet format (only verify, no changes)
      id: dotnet-format
      run: dotnet format --verbosity diagnostic --verify-no-changes V8ed/V8ed.csproj

    - name: Create Linter Comments
      if: steps.dotnet-format.outcome == 'failure'
      uses: actions/github-script@v7.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          for (const line of '${{ steps.dotnet-format.outputs.dotnet-format-output }}'.split('\n'))
            if (line.startsWith("  Line"))
              github.repos.createCommitComment({
                context.payload.pull_request.base.repo.owner.login,
                context.payload.pull_request.base.repo.name,
                commit_sha: context.payload.pull_request.head.sha,
                body: line.split(':').slice(3).join(':').trim(),
                path: line.split(':')[1].trim(),
                position: line.split(':')[2].trim()
              });
